apiVersion: v1
kind: Pod
metadata:
  name: order-gen
spec:
  containers:
  - args:
    - -broker=kafka-broker:9092
    - -topic=my-topic
    image: quay.io/numaio/numaflow-demo/dooreats-order-gen:v0.0.2
    imagePullPolicy: IfNotPresent
    name: main
