apiVersion: v1
kind: Namespace
metadata:
  name: sandbox-rollout-numalogic-demo
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: numalogic-demo-rollout
  namespace: sandbox-rollout-numalogic-demo
  labels:
    app: numalogic-rollout-demo
    app.kubernetes.io/instance: numalogic-rollout-demo
    applications.argoproj.io/app-name: numalogic-demo
    assetAlias: Intuit.sandbox.sandbox.numalogicdemo
    assetId: '4975369280839883999'
    buildType: maven
    env: demo-usw2-eks
    l1: sandbox
    l2: sandbox
spec:
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 1h # 1 hour
        - setWeight: 20
        - pause: {} # pause indefinitely
  replicas: 6
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: numalogic-rollout-demo
  template:
    metadata:
      labels:
        app: numalogic-rollout-demo
        applications.argoproj.io/app-name: numalogic-rollout-demo
        asset: Intuit.sandbox.sandbox.demorestapp
        assetAlias: Intuit.sandbox.sandbox.demorestapp
        assetId: '4975369280839883999'
        env: qal
        istio-injected: 'true'
        l1: sandbox
        l2: sandbox
    spec:
      containers:
        - name: app
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: docker.io/sarabala1979/numalogic-demo:yellow-error
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: service
              protocol: TCP
            - containerPort: 8490
              name: metric
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8080
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
  minReadySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: numalogic-demo-service
  namespace: sandbox-rollout-numalogic-demo
spec:
  ports:
    - name: service
      port: 8080
      targetPort: 8080
  selector:
    app: numalogic-rollout-demo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    iks-metric: actuator-prometheus
  name: numalogic-demo-service-metrics
  namespace: sandbox-rollout-numalogic-demo
spec:
  ports:
    - name: iks-metric
      port: 8490
      protocol: TCP
      targetPort: 8490
  selector:
    app: numalogic-rollout-demo
  type: ClusterIP
